import type { StoreConfig, StoreProduct } from "@/types/domain";

export const createTestStoreConfig = (workspaceId: string): StoreConfig => ({
  id: workspaceId,
  workspaceId,
  slug: "boutique-mode",
  name: "Boutique Mode Gabon",
  city: "Libreville",
  address: "Avenue Léon Mba, Quartier Louis",
  description: "Votre boutique de mode africaine et accessoires premium au Gabon. Collection exclusive de robes wax, pagnes et accessoires de qualité.",
  published: true,
  theme: {
    primaryColor: "#22c55e",
    accentColor: "#f59e0b",
    background: "light",
    typography: "sans",
  },
  page: {
    heroTitle: "Boutique Mode Gabon",
    heroSubtitle: "Découvrez notre collection exclusive de vêtements et accessoires africains",
    heroImage: null,
    highlights: [
      { title: "Livraison gratuite", description: "Pour toutes commandes supérieures à 50 000 FCFA" },
      { title: "Paiement sécurisé", description: "Mobile Money et cartes bancaires acceptées" },
      { title: "Retours faciles", description: "Sous 7 jours si non satisfait" },
    ],
    trustBadges: ["Certifié PRO.GA", "Paiement sécurisé", "Livraison rapide"],
  },
  metadata: {
    category: "mode",
    instagram: "@boutiquemodegabon",
    phone: "+241 07 XX XX XX",
  },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
});

export const createTestStoreProducts = (workspaceId: string): StoreProduct[] => [
  {
    id: crypto.randomUUID(),
    workspaceId,
    name: "Robe Wax Premium",
    description: "Robe élégante en tissu wax de qualité supérieure, design moderne et confortable. Disponible en plusieurs tailles et motifs.",
    price: 65000,
    currency: "XOF",
    sku: "RB-WAX-001",
    stock: 25,
    category: "Robes",
    imageUrl: null,
    status: "active",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    workspaceId,
    name: "Pagne Traditionnel",
    description: "Pagne en tissu de qualité premium, motifs authentiques. Parfait pour occasions spéciales.",
    price: 35000,
    currency: "XOF",
    sku: "PG-TRAD-001",
    stock: 40,
    category: "Pagnes",
    imageUrl: null,
    status: "active",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    workspaceId,
    name: "Chemise Africaine",
    description: "Chemise moderne avec imprimés africains, coupe ajustée. Idéale pour homme et femme.",
    price: 45000,
    currency: "XOF",
    sku: "CH-AFR-001",
    stock: 30,
    category: "Chemises",
    imageUrl: null,
    status: "active",
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    workspaceId,
    name: "Sac à Main en Rafia",
    description: "Sac à main élégant en rafia naturel, finitions en cuir. Solide et stylé.",
    price: 28000,
    currency: "XOF",
    sku: "SAC-RAF-001",
    stock: 15,
    category: "Accessoires",
    imageUrl: null,
    status: "active",
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    workspaceId,
    name: "Boucles d'Oreilles Artisanales",
    description: "Boucles d'oreilles en bois sculpté, design unique. Disponibles en plusieurs modèles.",
    price: 12000,
    currency: "XOF",
    sku: "BOU-ART-001",
    stock: 50,
    category: "Accessoires",
    imageUrl: null,
    status: "active",
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    workspaceId,
    name: "Ensemble Femme 3 pièces",
    description: "Ensemble complet (haut, jupe, foulard) en tissu wax. Couleur assortie.",
    price: 95000,
    currency: "XOF",
    sku: "ENS-3PC-001",
    stock: 12,
    category: "Ensembles",
    imageUrl: null,
    status: "active",
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    workspaceId,
    name: "Sandales en Cuir",
    description: "Sandales confortables en cuir véritable, semelle anti-dérapante. Plusieurs tailles disponibles.",
    price: 38000,
    currency: "XOF",
    sku: "SAN-CUIR-001",
    stock: 20,
    category: "Chaussures",
    imageUrl: null,
    status: "active",
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    workspaceId,
    name: "Collier Perles",
    description: "Collier en perles naturelles, design traditionnel. Longueur ajustable.",
    price: 22000,
    currency: "XOF",
    sku: "COL-PER-001",
    stock: 35,
    category: "Bijoux",
    imageUrl: null,
    status: "active",
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initTestStoreData = (workspaceId: string): { config: StoreConfig; products: StoreProduct[] } => {
  const config = createTestStoreConfig(workspaceId);
  const products = createTestStoreProducts(workspaceId);

  if (typeof window !== "undefined") {
    const storageKey = `proga.store.${workspaceId}`;
    localStorage.setItem(storageKey, JSON.stringify({ config, products }));
  }

  return { config, products };
};
